name: Continuous Integration

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test

  build-and-release-on-ubuntu-x86:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust target
      run: rustup target add x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu
    - name: Package tarball
      if: github.ref_type == 'tag'
      run: |
        VERSION="${GITHUB_REF_NAME}"
        tar -C target/x86_64-unknown-linux-gnu/release \
            -czf sarifup-${VERSION}-linux-x64.tar.gz \
            sarifup
    - name: Release ubuntu
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: sarifup-*-linux-x64.tar.gz


  build-and-release-on-macos:
    runs-on: macos-latest
    needs: test
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust targets
      run: rustup target add x86_64-apple-darwin aarch64-apple-darwin
    - name: Build macOS x64
      run: cargo build --release --target x86_64-apple-darwin
    - name: Build macOS arm64
      run: cargo build --release --target aarch64-apple-darwin
    - name: Package tarballs
      if: github.ref_type == 'tag'
      run: |
        VERSION="${GITHUB_REF_NAME}"
        tar -C target/x86_64-apple-darwin/release \
            -czf sarifup-${VERSION}-macos-x64.tar.gz \
            sarifup
        tar -C target/aarch64-apple-darwin/release \
            -czf sarifup-${VERSION}-macos-arm64.tar.gz \
            sarifup
    - name: Release macOS
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: sarifup-*-macos-*.tar.gz
  
  build-and-release-on-windows:
    runs-on: windows-latest
    needs: test
    permissions:
      contents: write
  steps:
    - uses: actions/checkout@v4
    - name: Install Rust target
      run: rustup target add x86_64-pc-windows-msvc
    - name: Build
      run: cargo build --release --target x86_64-pc-windows-msvc
    - name: Package tarball
      if: github.ref_type == 'tag'
      shell: bash
      run: |
        VERSION="${GITHUB_REF_NAME}"
        tar -C target/x86_64-pc-windows-msvc/release \
            -czf sarifup-${VERSION}-windows-x64.tar.gz \
            sarifup.exe
    - name: Release windows
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: sarifup-*-windows-x64.tar.gz

